version: '3.7'

services:
  app:
    build:
      context: .
    environment: 
      - SECRET_KEY=${SECRET_KEY}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
    
  proxy:
    build:
      context: ./proxy
    ports:
      - "8080:8080"
    depends_on: 
      - app
    
